# action.yml
name: "Blurry Build"
description: "Builds a static site using Blurry, a static site generator focused on page speed and SEO"
inputs:
  site-root:
    description: "Path to the site root, i.e. a directory containing blurry.toml"
    required: true
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.site-root }}
branding:
  icon: eye
  color: yellow
